name: Deploy Go Bot Database Migrations

on:
  push:
    branches: [ "main" ]

jobs:
  image: 
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/protein-bot:latest
            ghcr.io/${{ github.repository_owner }}/protein-bot:${{ env.SHORT_SHA }}
  migrate:
    runs-on: ubuntu-latest
    needs: image   # <--- wait for image job to succeed
    environment: production
    env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ vars.DB_HOST }}
        DB_PORT: ${{ vars.DB_PORT }}
        DB_NAME: ${{ vars.DB_NAME }}
    steps:
      - uses: actions/checkout@v3

      - name: Debug environment
        run: |
          echo "Current directory: $(pwd)"
          echo "DB_HOST: $DB_HOST"
          echo "DB_PORT: $DB_PORT"

      - name: Run DB migrations
        run: |
          make migrate-up


